backend:
  name: git-gateway
  branch: main

media_folder: "client/public/uploads"
public_folder: "/uploads"

collections:
  - name: "characters"
    label: "Characters"
    folder: "client/public/content/characters"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "locations"
    label: "Locations"
    folder: "client/public/content/locations"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
